## StarShip: ~/.config/starship.toml

add_newline = true
command_timeout = 1

format = """\
$os$directory$git_branch$git_status$kubernetes
❯ """


[character]
error_symbol = "[✖](maroon) "

[os]
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ' '
Macos = '󰀵 '

[git_status]
format = '([\($all_status$ahead_behind\) ]($style))'
style = 'green'
conflicted = '[ confliced=${count}](red)'
up_to_date = '[󰘽 ](green)'
untracked = '[󰋗 ${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green)'
modified = '[󰛿 ${count}](yellow) '
staged = '[󰐗 staged=${count}](green)'
renamed = '[󱍸 renamed=${count}](yellow)'
deleted = '[󰍶 ${count}](red) '

[directory]
truncation_length = 4
truncation_symbol = '…/'
style = "bold lavender"
#read_only_style = '197'
read_only_style = 'red'
read_only = '  ' 
format = ' [$path]($style)[$read_only]($read_only_style) '

# Shows kubernetes context and namespace
[kubernetes]
format = '''via [$symbol$context](blue)\[[$namespace](bold yellow)\]'''
symbol = '󱃾 '
disabled = false

# Disabled Modules
[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true


# Sets user-defined palette
palette = "catppuccin_mocha"


# Catppuccin Color Themes (https://github.com/catppuccin)
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
