
[env]
TERM = "xterm-256color"

### opacity and blur
[window]
opacity = 1 # 0.95
padding = {x=3,y=3}
# decorations = "none"

### Font Config
[font]
size = 10.0
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


### Scrolling
[scrolling]
  history = 10000
  multiplier = 5

### Moved marked text to clipboard
[selection]
save_to_clipboard = true

[general]

###  Live Reload
live_config_reload = true

### Import Catppuccin theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
